# Generated by Django 3.2 on 2022-04-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220415_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='friendly_name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.SlugField(max_length=254, unique=True),
        ),
    ]
