# Generated by Django 3.2 on 2022-04-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220415_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='friendly_name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='friendly_name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='friendly_name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='name',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='friendly_name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.SlugField(max_length=254, unique=True),
        ),
    ]
