# Generated by Django 3.2 on 2022-04-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
