# Generated by Django 3.2 on 2022-05-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
