# Generated by Django 3.2 on 2022-05-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_total',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
